project_id = "kytoqxnxjkpmfvkpaddf"
[functions.chat]
verify_jwt = false

[functions.exam-info]
verify_jwt = false

[functions.linkage]
verify_jwt = false

[functions.planner]
verify_jwt = false

[functions.chapter-summary]
verify_jwt = false

[functions.quiz-generator]
verify_jwt = false
[functions.copy-checker]
verify_jwt = false
