import { useState } from "react";
import { motion } from "framer-motion";
import { CheckCircle2, Circle, Flame, BookOpen, Sparkles, TrendingUp } from "lucide-react";
import { DashboardSidebar } from "@/components/DashboardSidebar";
import { CountdownRing } from "@/components/CountdownRing";
import { PageTransition } from "@/components/PageTransition";

const initialTargets = [
  { id: 1, label: "IND-AS 115 — Revenue Recognition (Module 2, Ch. 4)", time: "1h 30m", done: true },
  { id: 2, label: "Direct Tax: Sec 80C–80U deductions revision", time: "45m", done: true },
  { id: 3, label: "Audit: SA 700 & SA 705 — Modified Opinions", time: "1h", done: false },
  { id: 4, label: "SFM: Portfolio Theory — solve RTP Q3 to Q7", time: "1h 15m", done: false },
  { id: 5, label: "Bilingual Translator: practice 5 GST scenarios", time: "30m", done: false },
];

const week = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const intensity = [3, 4, 2, 4, 3, 2, 1]; // 0-4 scale

const Dashboard = () => {
  const [targets, setTargets] = useState(initialTargets);
  const completed = targets.filter((t) => t.done).length;

  return (
    <PageTransition>
      <div className="flex min-h-screen w-full bg-background">
        <DashboardSidebar />

        <main className="flex-1 px-6 lg:px-10 py-8 max-w-7xl mx-auto w-full">
          {/* Header */}
          <div className="flex flex-wrap items-end justify-between gap-4 mb-8">
            <div>
              <p className="text-sm text-muted-foreground">Good evening, Aarav 👋</p>
              <h1 className="text-3xl md:text-4xl font-bold tracking-tight mt-1">
                Your <span className="text-gradient">CA Final</span> command centre.
              </h1>
            </div>
            <div className="flex items-center gap-2 glass rounded-full px-4 py-2 text-sm">
              <Flame className="h-4 w-4 text-accent" /> 14-day streak active
            </div>
          </div>

          {/* Top widget grid */}
          <div className="grid lg:grid-cols-3 gap-5 mb-8">
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              className="lg:col-span-2 glass-strong rounded-2xl p-6"
            >
              <CountdownRing progress={42} />
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="glass-strong rounded-2xl p-6 flex flex-col"
            >
              <div className="flex items-center justify-between">
                <p className="text-xs uppercase tracking-widest text-muted-foreground">Today</p>
                <Sparkles className="h-4 w-4 text-accent" />
              </div>
              <p className="mt-3 text-4xl font-bold tabular-nums">
                {completed}<span className="text-muted-foreground">/{targets.length}</span>
              </p>
              <p className="text-sm text-muted-foreground">targets completed</p>
              <div className="mt-4 h-2 rounded-full bg-secondary overflow-hidden">
                <div
                  className="h-full bg-gradient-primary transition-all"
                  style={{ width: `${(completed / targets.length) * 100}%` }}
                />
              </div>
              <div className="mt-auto pt-5 flex items-center gap-2 text-xs text-success">
                <TrendingUp className="h-3.5 w-3.5" /> +12% vs last week
              </div>
            </motion.div>
          </div>

          {/* Two column: targets + calendar */}
          <div className="grid lg:grid-cols-3 gap-5">
            <div className="lg:col-span-2 glass-strong rounded-2xl p-6">
              <div className="flex items-center justify-between mb-5">
                <div className="flex items-center gap-2">
                  <BookOpen className="h-4 w-4 text-primary" />
                  <h2 className="font-semibold">Today's Targets</h2>
                </div>
                <span className="text-xs text-muted-foreground">Auto-generated by Backlog AI</span>
              </div>

              <ul className="space-y-2">
                {targets.map((t) => (
                  <li key={t.id}>
                    <button
                      onClick={() =>
                        setTargets((prev) => prev.map((x) => (x.id === t.id ? { ...x, done: !x.done } : x)))
                      }
                      className={`w-full text-left flex items-center gap-3 p-3 rounded-xl border border-border/50 transition-all ${
                        t.done ? "bg-secondary/40" : "bg-card/40 hover:bg-secondary/40"
                      }`}
                    >
                      {t.done ? (
                        <CheckCircle2 className="h-5 w-5 text-success shrink-0" />
                      ) : (
                        <Circle className="h-5 w-5 text-muted-foreground shrink-0" />
                      )}
                      <span className={`flex-1 text-sm ${t.done ? "line-through text-muted-foreground" : ""}`}>
                        {t.label}
                      </span>
                      <span className="text-xs text-muted-foreground tabular-nums">{t.time}</span>
                    </button>
                  </li>
                ))}
              </ul>
            </div>

            <div className="glass-strong rounded-2xl p-6">
              <h2 className="font-semibold mb-1">Study calendar</h2>
              <p className="text-xs text-muted-foreground mb-5">Last 7 days · hours studied</p>
              <div className="grid grid-cols-7 gap-2">
                {week.map((d, i) => (
                  <div key={d} className="flex flex-col items-center gap-2">
                    <div
                      className={`h-16 w-full rounded-lg border border-border/50 grid place-items-end p-1 ${
                        intensity[i] >= 3 ? "bg-gradient-primary glow-primary" : "bg-secondary/60"
                      }`}
                    >
                      <span className="text-[10px] text-primary-foreground/90 font-semibold">{intensity[i]}h</span>
                    </div>
                    <span className="text-[10px] text-muted-foreground">{d}</span>
                  </div>
                ))}
              </div>

              <div className="mt-6 rounded-xl glass p-4">
                <p className="text-xs text-muted-foreground">Next mock</p>
                <p className="font-semibold mt-1">ICAI MTP — Series I</p>
                <p className="text-xs text-muted-foreground">in 9 days · Paper 1: Financial Reporting</p>
              </div>
            </div>
          </div>
        </main>
      </div>
    </PageTransition>
  );
};

export default Dashboard;