import { useEffect, useState } from "react";
import { DashboardSidebar } from "@/components/DashboardSidebar";
import { PageTransition } from "@/components/PageTransition";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";
import { FileText, Upload, Sparkles, Download, Trash2, Loader2 } from "lucide-react";
import jsPDF from "jspdf";

type Note = {
  id: string; uploaded_by: string; course: string; level: string;
  subject: string; chapter: string; title: string;
  file_path: string | null; is_ai_generated: boolean; is_private: boolean;
};

const COURSES = ["CA", "CS", "CMA"];
const LEVELS = ["Foundation", "Inter", "Final", "Executive", "Professional"];

const Notes = () => {
  const { user } = useAuth();
  const [notes, setNotes] = useState<Note[]>([]);
  const [loading, setLoading] = useState(true);
  const [course, setCourse] = useState("CA");
  const [level, setLevel] = useState("Final");
  const [subject, setSubject] = useState("");
  const [chapter, setChapter] = useState("");
  const [title, setTitle] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [generating, setGenerating] = useState(false);

  const load = async () => {
    setLoading(true);
    const { data, error } = await supabase.from("notes").select("*").order("created_at", { ascending: false });
    if (error) toast.error(error.message);
    else setNotes((data ?? []) as Note[]);
    setLoading(false);
  };
  useEffect(() => { load(); }, []);

  const upload = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user || !file || !subject || !chapter || !title) return toast.error("Fill all fields and pick a PDF");
    setUploading(true);
    const path = `${user.id}/${Date.now()}-${file.name}`;
    const { error: upErr } = await supabase.storage.from("notes").upload(path, file, { contentType: "application/pdf" });
    if (upErr) { setUploading(false); return toast.error(upErr.message); }
    const { error } = await supabase.from("notes").insert({
      uploaded_by: user.id, course, level, subject, chapter, title, file_path: path,
    });
    setUploading(false);
    if (error) return toast.error(error.message);
    toast.success("Note uploaded");
    setFile(null); setTitle(""); setChapter(""); setSubject("");
    load();
  };

  const aiGenerate = async () => {
    if (!user || !subject || !chapter) return toast.error("Pick subject and chapter first");
    setGenerating(true);
    try {
      const resp = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}` },
        body: JSON.stringify({
          messages: [{
            role: "user",
            content: `Generate concise, exam-ready chapter notes for ${course} ${level} students. Subject: ${subject}. Chapter: ${chapter}. Use ICAI/ICSI/ICMAI-style headings, definitions, key sections/standards, illustrations and a 5-point summary at the end. Plain text only.`,
          }],
          bilingual: false,
          stream: false,
        }),
      });
      const text = await resp.text();
      // Backend streams SSE; collect content tokens
      let body = "";
      text.split("\n").forEach((line) => {
        if (!line.startsWith("data: ")) return;
        const json = line.slice(6).trim();
        if (json === "[DONE]") return;
        try { const p = JSON.parse(json); body += p.choices?.[0]?.delta?.content ?? ""; } catch {}
      });
      if (!body) body = text;

      const pdf = new jsPDF({ unit: "pt", format: "a4" });
      const margin = 48;
      const pageW = pdf.internal.pageSize.getWidth();
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(18);
      pdf.text(`${chapter}`, margin, margin);
      pdf.setFont("helvetica", "normal"); pdf.setFontSize(11); pdf.setTextColor(110);
      pdf.text(`${course} ${level} · ${subject}  ·  Generated by EduElite AI`, margin, margin + 18);
      pdf.setTextColor(20); pdf.setFontSize(11);
      const lines = pdf.splitTextToSize(body, pageW - margin * 2);
      let y = margin + 44;
      lines.forEach((ln: string) => {
        if (y > pdf.internal.pageSize.getHeight() - margin) { pdf.addPage(); y = margin; }
        pdf.text(ln, margin, y); y += 14;
      });
      const fname = `${course}-${level}-${chapter.replace(/\s+/g, "-")}.pdf`;
      const blob = pdf.output("blob");
      const path = `${user.id}/ai-${Date.now()}-${fname}`;
      const { error: upErr } = await supabase.storage.from("notes").upload(path, blob, { contentType: "application/pdf" });
      if (upErr) throw upErr;
      const { error } = await supabase.from("notes").insert({
        uploaded_by: user.id, course, level, subject, chapter,
        title: `${chapter} — AI notes`, file_path: path, is_ai_generated: true, is_private: false,
      });
      if (error) throw error;
      toast.success("AI notes generated");
      load();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Generation failed");
    } finally {
      setGenerating(false);
    }
  };

  const download = async (n: Note) => {
    if (!n.file_path) return;
    const { data } = await supabase.storage.from("notes").createSignedUrl(n.file_path, 300);
    if (data?.signedUrl) window.open(data.signedUrl, "_blank");
  };

  const remove = async (n: Note) => {
    if (n.uploaded_by !== user?.id) return;
    if (n.file_path) await supabase.storage.from("notes").remove([n.file_path]);
    await supabase.from("notes").delete().eq("id", n.id);
    setNotes((x) => x.filter((m) => m.id !== n.id));
  };

  const filtered = notes.filter((n) => n.course === course && n.level === level);

  return (
    <PageTransition>
      <div className="flex min-h-screen w-full bg-background">
        <DashboardSidebar />
        <main className="flex-1 px-6 lg:px-10 py-8 max-w-6xl mx-auto w-full">
          <h1 className="font-display text-3xl font-bold tracking-tight">Notes Library</h1>
          <p className="text-sm text-muted-foreground mt-1">Browse chapter PDFs or generate fresh AI notes for any chapter.</p>

          <div className="mt-6 grid lg:grid-cols-3 gap-5">
            <form onSubmit={upload} className="glass-strong rounded-2xl p-5 space-y-3 lg:col-span-1">
              <h2 className="font-semibold flex items-center gap-2"><Upload className="h-4 w-4 text-primary" /> Add note</h2>
              <div className="grid grid-cols-2 gap-2">
                <select value={course} onChange={(e) => setCourse(e.target.value)} className="glass rounded-lg px-3 py-2 text-sm bg-transparent">
                  {COURSES.map((c) => <option key={c} className="bg-background">{c}</option>)}
                </select>
                <select value={level} onChange={(e) => setLevel(e.target.value)} className="glass rounded-lg px-3 py-2 text-sm bg-transparent">
                  {LEVELS.map((c) => <option key={c} className="bg-background">{c}</option>)}
                </select>
              </div>
              <input value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="Subject (e.g. Audit)" className="w-full glass rounded-lg px-3 py-2 text-sm bg-transparent outline-none" />
              <input value={chapter} onChange={(e) => setChapter(e.target.value)} placeholder="Chapter (e.g. SA 700)" className="w-full glass rounded-lg px-3 py-2 text-sm bg-transparent outline-none" />
              <input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Title shown in library" className="w-full glass rounded-lg px-3 py-2 text-sm bg-transparent outline-none" />
              <input type="file" accept="application/pdf" onChange={(e) => setFile(e.target.files?.[0] ?? null)} className="w-full text-xs" />
              <button disabled={uploading} className="btn-3d w-full inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-primary py-2.5 text-sm font-semibold text-primary-foreground glow-primary disabled:opacity-50">
                {uploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}
                Upload PDF
              </button>
              <button type="button" onClick={aiGenerate} disabled={generating} className="btn-3d w-full inline-flex items-center justify-center gap-2 rounded-xl glass-strong py-2.5 text-sm font-semibold disabled:opacity-50">
                {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4 text-accent" />}
                Generate AI notes PDF
              </button>
            </form>

            <div className="lg:col-span-2 glass-strong rounded-2xl p-5">
              <div className="flex items-center gap-2 mb-4">
                <FileText className="h-4 w-4 text-primary" />
                <h2 className="font-semibold">{course} · {level}</h2>
                <span className="text-xs text-muted-foreground ml-auto">{filtered.length} notes</span>
              </div>
              {loading ? <p className="text-sm text-muted-foreground">Loading…</p> : filtered.length === 0 ? (
                <p className="text-sm text-muted-foreground">No notes yet for this filter. Upload one or generate with AI.</p>
              ) : (
                <ul className="space-y-2">
                  {filtered.map((n) => (
                    <li key={n.id} className="flex items-center gap-3 p-3 rounded-xl border border-border/50 bg-card/40">
                      <div className="h-9 w-9 rounded-lg bg-secondary grid place-items-center"><FileText className="h-4 w-4 text-primary" /></div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium truncate">{n.title}</p>
                        <p className="text-[10px] uppercase tracking-widest text-muted-foreground">{n.subject} · {n.chapter}{n.is_ai_generated ? " · AI" : ""}</p>
                      </div>
                      <button onClick={() => download(n)} className="text-muted-foreground hover:text-primary"><Download className="h-4 w-4" /></button>
                      {n.uploaded_by === user?.id && (
                        <button onClick={() => remove(n)} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></button>
                      )}
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </main>
      </div>
    </PageTransition>
  );
};
export default Notes;